### ISSUE TITLE
[meta] Tracking issue for merging api22 into master

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-events#117]
* [ ] Redaction events - #116
* [ ] Room event types without `room_id` (`MessageEventStub` & `StateEventStub`)
* [ ] `StrippedStateEventStub` (see `StrippedState` in the spec)
* [ ] Event enums
  * [ ] Primary event kinds (`AnyBasicEvent`, `AnyEphemeralRoomEvent`, `AnyMessageEvent`, `AnyStateEvent`)
  * [ ] "Dependent" secondary event kinds, where variants are the same  as for one of the primary event kinds (`AnyMessageEventStub`, `AnyStateEventStub`, `AnyStrippedStateEventStub`)
  * [ ] "Independent" secondary event kinds, where variants are independent of primary event kinds (`AnyToDeviceEvent`)
